/** @format */
import {Inter} from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';
import ReduxProvider from '@/redux/provider';
import {ChatContextProvider} from '@/context/ChatContext';
import {AppContextProvider} from '@/context/AppContext';

const inter = Inter({subsets: ['latin']});

export const metadata = {
   title: 'Tour Travel',
   description: 'Generated by create next app',
};

export default function RootLayout({children}) {
   return (
      <html lang='en'>
         <body className={inter.className}>
            <AppContextProvider>
               <ReduxProvider>
                  <ChatContextProvider>
                     <Navbar />
                     <div style={{marginTop: '89px'}}>{children}</div>
                     <Footer />
                  </ChatContextProvider>
               </ReduxProvider>
            </AppContextProvider>
         </body>
      </html>
   );
}
